# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'locker.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 589)
        MainWindow.setMinimumSize(QtCore.QSize(659, 589))
        MainWindow.setMaximumSize(QtCore.QSize(659, 589))
        MainWindow.setStyleSheet("background-color: rgb(69, 73, 74);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(69, 73, 74);")
        self.centralwidget.setObjectName("centralwidget")
        self.textInput = QtWidgets.QLineEdit(self.centralwidget)
        self.textInput.setGeometry(QtCore.QRect(10, 10, 641, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textInput.setFont(font)
        self.textInput.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.textInput.setText("")
        self.textInput.setFrame(False)
        self.textInput.setAlignment(QtCore.Qt.AlignCenter)
        self.textInput.setObjectName("textInput")
        self.labelInfo = QtWidgets.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(10, 500, 641, 71))
        self.labelInfo.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.labelInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setWordWrap(True)
        self.labelInfo.setObjectName("labelInfo")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 487, 641, 10))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(530, 80, 121, 41))
        self.buttonStart.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.buttonStart.setObjectName("buttonStart")
        self.listView = QtWidgets.QTreeWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 132, 641, 351))
        self.listView.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.listView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listView.setObjectName("listView")
        self.listView.headerItem().setText(0, "1")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 80, 341, 41))
        self.frame.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.radioEncryptDecrypt = QtWidgets.QRadioButton(self.frame)
        self.radioEncryptDecrypt.setObjectName("radioEncryptDecrypt")
        self.gridLayout.addWidget(self.radioEncryptDecrypt, 0, 2, 1, 1)
        self.radioEncrypt = QtWidgets.QRadioButton(self.frame)
        self.radioEncrypt.setObjectName("radioEncrypt")
        self.gridLayout.addWidget(self.radioEncrypt, 0, 0, 1, 1)
        self.radioDecrypt = QtWidgets.QRadioButton(self.frame)
        self.radioDecrypt.setObjectName("radioDecrypt")
        self.gridLayout.addWidget(self.radioDecrypt, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(360, 80, 121, 41))
        self.frame_2.setStyleSheet("background-color: rgb(60, 63, 65);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBoxEncryptOnlyFiles = QtWidgets.QCheckBox(self.frame_2)
        self.checkBoxEncryptOnlyFiles.setChecked(True)
        self.checkBoxEncryptOnlyFiles.setObjectName("checkBoxEncryptOnlyFiles")
        self.gridLayout_2.addWidget(self.checkBoxEncryptOnlyFiles, 0, 0, 1, 1)
        self.checkBoxRenameOutput = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxRenameOutput.setGeometry(QtCore.QRect(20, 570, 241, 20))
        self.checkBoxRenameOutput.setObjectName("checkBoxRenameOutput")
        self.checkBoxSetPassword = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxSetPassword.setGeometry(QtCore.QRect(300, 570, 241, 20))
        self.checkBoxSetPassword.setObjectName("checkBoxSetPassword")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textInput.setPlaceholderText(_translate("MainWindow", "Drag and Drop Files / Folders to Lock or unlocked here...."))
        self.labelInfo.setText(_translate("MainWindow", "Info"))
        self.buttonStart.setText(_translate("MainWindow", "Start"))
        self.radioEncryptDecrypt.setText(_translate("MainWindow", "Encrypt/Decrypt"))
        self.radioEncrypt.setText(_translate("MainWindow", "Encrypt"))
        self.radioDecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.checkBoxEncryptOnlyFiles.setText(_translate("MainWindow", "Files Only"))
        self.checkBoxRenameOutput.setText(_translate("MainWindow", "Rename Output(random name)"))
        self.checkBoxSetPassword.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Check to</span>: <span style=\" font-style:italic;\">Set Encryption/Decription Password for curent task.</span></p><p><span style=\" font-weight:600;\">Uncheck to</span>:<span style=\" font-style:italic;\"> Use default Password.</span></p><p><span style=\" font-weight:600; text-decoration: underline;\">Warning!</span></p><p><span style=\" font-style:italic;\">Don\'t forget the password used for encryption. Your file will not be able to be decrypted if you forget password.</span></p><p><br/></p></body></html>"))
        self.checkBoxSetPassword.setText(_translate("MainWindow", "Set Encrypting/Decrypting Password"))

